version: "3.8"
services:
  mongodb:
    image : "mongo:4.2.16"
    container_name: "mongo-db-latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    ports:
      - "27018:27017"
    restart: unless-stopped

